# Generated by Django 6.0.5 on 2026-05-15 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_vehiculo'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordentrabajo',
            options={'ordering': ['-fecha_ingreso'], 'verbose_name': 'Orden de Trabajo'},
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='costo_estimado',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='diagnostico',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='fecha_entrega',
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='notas_internas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('recibido', 'Recibido'), ('diagnostico', 'Diagnóstico'), ('aprobado', 'Aprobado'), ('en_proceso', 'En proceso'), ('esperando_repuestos', 'Esperando repuestos'), ('en_pruebas', 'En pruebas'), ('finalizado', 'Finalizado'), ('entregado', 'Entregado')], default='recibido', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.vehiculo'),
        ),
        migrations.CreateModel(
            name='FotoProcesoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='ordenes/%Y/%m/%d/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('paso_numero', models.IntegerField(default=1)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_proceso', to='servicios.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Foto del Proceso',
                'ordering': ['paso_numero'],
            },
        ),
        migrations.CreateModel(
            name='PasoProcesoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completado', 'Completado')], default='pendiente', max_length=20)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('tiempo_minutos', models.IntegerField(blank=True, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos_proceso', to='servicios.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Paso del Proceso',
                'ordering': ['numero'],
            },
        ),
    ]
