# Generated by Django 6.0.5 on 2026-05-13 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_vehiculo'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('nomina', 'Nómina'), ('arriendo', 'Arriendo'), ('servicios', 'Servicios públicos'), ('repuestos', 'Repuestos'), ('herramientas', 'Herramientas'), ('marketing', 'Marketing'), ('otros', 'Otros')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('comprobante', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='pendiente', max_length=15)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata')], default='efectivo', max_length=15)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='clientes.cliente')),
                ('orden', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='servicios.ordentrabajo')),
            ],
            options={
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
