# Generated by Django 5.0.14 on 2026-05-15 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_id_alter_vehiculo_id'),
        ('contabilidad', '0001_initial'),
        ('servicios', '0003_alter_fotoprocesoorden_id_alter_ordentrabajo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='borrador', max_length=15)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vigencia_dias', models.IntegerField(default=15)),
                ('notas', models.TextField(blank=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='clientes.cliente')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='servicios.ordentrabajo')),
            ],
            options={
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='LineaCotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('servicio', 'Servicio / Mano de obra'), ('repuesto', 'Repuesto')], default='servicio', max_length=10)),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('precio_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='contabilidad.cotizacion')),
            ],
            options={
                'verbose_name_plural': 'Lineas de Cotizacion',
            },
        ),
    ]
