# Generated by Django 6.0.5 on 2026-05-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_alter_cotizacion_id_alter_factura_id_alter_gasto_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='aplica_iva',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='factura',
            name='aplica_iva',
            field=models.BooleanField(default=False),
        ),
    ]
