# Generated by Django 6.0.5 on 2026-05-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_cotizacion_aplica_iva_factura_aplica_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineacotizacion',
            name='precio_costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lineafactura',
            name='precio_costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
