# Generated by Django 6.0.5 on 2026-06-01 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_alter_fotoprocesoorden_id_alter_ordentrabajo_id_and_more'),
        ('usuarios', '0002_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('cargo', models.CharField(blank=True, max_length=50)),
                ('tipo', models.CharField(choices=[('tecnico', 'Técnico'), ('contabilidad', 'Contabilidad'), ('admin', 'Administrador'), ('otro', 'Otro')], default='tecnico', max_length=20)),
                ('tipo_pago', models.CharField(choices=[('fijo', 'Salario fijo'), ('servicio', 'Por servicio'), ('mixto', 'Mixto')], default='servicio', max_length=20)),
                ('salario_base', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('porcentaje_mano_obra', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PagoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('salario_base', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_servicios', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=10)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomina', to='usuarios.empleado')),
            ],
            options={
                'verbose_name': 'Pago de nómina',
                'verbose_name_plural': 'Pagos de nómina',
                'ordering': ['-periodo_fin'],
            },
        ),
        migrations.CreateModel(
            name='PagoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('monto_orden', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('monto_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='usuarios.empleado')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_tecnico', to='servicios.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Pago por servicio',
                'verbose_name_plural': 'Pagos por servicio',
                'ordering': ['-fecha'],
            },
        ),
    ]
