# Generated by Django 6.0.5 on 2026-06-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_empleado_pagonomina_pagoservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='aplica_comision',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empleado',
            name='porcentaje_comision',
            field=models.DecimalField(decimal_places=2, default=10, help_text='% de comisión adicional sobre el total de la orden', max_digits=5),
        ),
        migrations.AddField(
            model_name='pagoservicio',
            name='aplica_comision',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagoservicio',
            name='monto_comision',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pagoservicio',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
