# Generated by Django 6.0.5 on 2026-05-14 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_vehiculo'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Mi Taller', max_length=100)),
                ('hora_apertura', models.TimeField(default='08:00')),
                ('hora_cierre', models.TimeField(default='18:00')),
                ('max_citas_hora', models.IntegerField(default=4)),
                ('sabado_activo', models.BooleanField(default=True)),
                ('sabado_apertura', models.TimeField(default='08:00')),
                ('sabado_cierre', models.TimeField(default='13:00')),
                ('whatsapp_numero', models.CharField(blank=True, max_length=20)),
                ('mensaje_confirmacion', models.TextField(default='Hola {nombre}! Tu cita fue confirmada para el {fecha} a las {hora}.')),
            ],
            options={
                'verbose_name': 'Configuracion del Taller',
            },
        ),
        migrations.CreateModel(
            name='DiaEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('tipo', models.CharField(choices=[('festivo', 'Festivo nacional'), ('bloqueado', 'Dia bloqueado'), ('especial', 'Horario especial')], max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('apertura', models.TimeField(blank=True, null=True)),
                ('cierre', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dia Especial',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo', models.CharField(choices=[('normal', 'Normal'), ('especial', 'Especial fuera de horario')], default='normal', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_cumplida', 'No cumplida')], default='pendiente', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('tecnico', models.CharField(blank=True, max_length=100)),
                ('notas_taller', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='clientes.cliente')),
                ('orden', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cita_origen', to='servicios.ordentrabajo')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='clientes.vehiculo')),
            ],
            options={
                'verbose_name': 'Cita',
                'ordering': ['fecha', 'hora'],
            },
        ),
    ]
