# Generated by Django 6.0.5 on 2026-05-14 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamiento', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link_temporal', to='servicios.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Link Temporal',
            },
        ),
    ]
