# Generated by Django 6.0.5 on 2026-05-13 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('linea', models.CharField(max_length=50)),
                ('modelo', models.IntegerField()),
                ('cilindraje', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('kilometraje', models.IntegerField(default=0)),
                ('tipo', models.CharField(choices=[('moto', 'Motocicleta'), ('carro', 'Automóvil'), ('bicicleta', 'Bicicleta Eléctrica')], default='moto', max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('en_servicio', 'En Servicio'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
            },
        ),
    ]
