# Generated by Django 6.0.5 on 2026-05-22 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_id_alter_vehiculo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('puntos_req', models.IntegerField()),
                ('tipo', models.CharField(choices=[('descuento', 'Descuento porcentaje'), ('servicio', 'Servicio gratis')], max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('activa', models.BooleanField(default=True)),
                ('imagen', models.CharField(default='🎁', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='HistorialPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ganado', 'Puntos ganados'), ('canjeado', 'Puntos canjeados'), ('ajuste', 'Ajuste manual')], max_length=10)),
                ('puntos', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_puntos', to='clientes.cliente')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
