# Generated by Django 6.0.5 on 2026-06-02 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_promocion_alter_cliente_id_alter_vehiculo_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocion',
            options={'ordering': ['puntos_req']},
        ),
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['-fecha_ingreso'], 'verbose_name': 'Vehículo', 'verbose_name_plural': 'Vehículos'},
        ),
    ]
